stages:
  train_object_classification:
    desc: Train the object classification model using EEG data.
    cmd: uv run python src/object_classification.py
    deps:
      - src/
      - configs/
    params:
      - configs/config.yaml:
          - batch_size
          - granularity
          - subject
          - metric
          - output_dir
      - configs/model/eegnet.yaml:
          - epochs
          - optimizer.type
          - optimizer.lr
          - optimizer.weight_decay
          - optimizer.momentum
    outs:
      - path: outputs/
        cache: false
        persist: true
