dataset_dir: data/
granularity: fine
subject: 0
batch_size: 40
output_dir: outputs/
metric: wt

model:
  name: mlp
  type: deep
  feature_type: time
  epochs: 1000
  optimizer:
    type: sgd
    lr: 0.0001
    weight_decay: 0.0001
    momentum: 0.9
