dataset_dir: data/
granularity: fine
subject: -1
batch_size: 40
output_dir: outputs/
metric: ct

model:
  name: mlp
  type: deep
  feature_type: freq
  epochs: 1000
  optimizer:
    type: sgd
    lr: 0.0001
    weight_decay: 0.0001
    momentum: 0.9
