name: semantic
type: deep
feature_type: time
epochs: 300

backbone: transformer
n_channels: 62
seq_len: 400
patch_len: 20
embed_dim: 256
nn_hidden_dim: 256
num_heads: 8
depth: 4
dropout: 0.1
projection_dim: 128

triplet_margin: 0.2
samples_per_class: 4  # samples per class per batch for balanced triplet mining
ema_decay: 0.996

optimizer:
  type: adam
  lr: 0.0001
  weight_decay: 0.0001
